/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BacklogRouteImport } from './routes/backlog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsMetadata5RouteImport } from './routes/settings.metadata5'
import { Route as SettingsMetadata4RouteImport } from './routes/settings.metadata4'
import { Route as SettingsMetadata3RouteImport } from './routes/settings.metadata3'
import { Route as SettingsMetadata2RouteImport } from './routes/settings.metadata2'
import { Route as SettingsMetadata1RouteImport } from './routes/settings.metadata1'
import { Route as BacklogEditGameIdRouteImport } from './routes/backlog.edit.$gameId'
import { Route as BacklogEditGameIdIndexRouteImport } from './routes/backlog.edit.$gameId.index'
import { Route as BacklogEditGameIdReviewRouteImport } from './routes/backlog.edit.$gameId.review'
import { Route as BacklogEditGameIdMetadataRouteImport } from './routes/backlog.edit.$gameId.metadata'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRoute = BacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMetadata5Route = SettingsMetadata5RouteImport.update({
  id: '/metadata5',
  path: '/metadata5',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMetadata4Route = SettingsMetadata4RouteImport.update({
  id: '/metadata4',
  path: '/metadata4',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMetadata3Route = SettingsMetadata3RouteImport.update({
  id: '/metadata3',
  path: '/metadata3',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMetadata2Route = SettingsMetadata2RouteImport.update({
  id: '/metadata2',
  path: '/metadata2',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMetadata1Route = SettingsMetadata1RouteImport.update({
  id: '/metadata1',
  path: '/metadata1',
  getParentRoute: () => SettingsRoute,
} as any)
const BacklogEditGameIdRoute = BacklogEditGameIdRouteImport.update({
  id: '/edit/$gameId',
  path: '/edit/$gameId',
  getParentRoute: () => BacklogRoute,
} as any)
const BacklogEditGameIdIndexRoute = BacklogEditGameIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BacklogEditGameIdRoute,
} as any)
const BacklogEditGameIdReviewRoute = BacklogEditGameIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => BacklogEditGameIdRoute,
} as any)
const BacklogEditGameIdMetadataRoute =
  BacklogEditGameIdMetadataRouteImport.update({
    id: '/metadata',
    path: '/metadata',
    getParentRoute: () => BacklogEditGameIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/settings/metadata1': typeof SettingsMetadata1Route
  '/settings/metadata2': typeof SettingsMetadata2Route
  '/settings/metadata3': typeof SettingsMetadata3Route
  '/settings/metadata4': typeof SettingsMetadata4Route
  '/settings/metadata5': typeof SettingsMetadata5Route
  '/settings/': typeof SettingsIndexRoute
  '/backlog/edit/$gameId': typeof BacklogEditGameIdRouteWithChildren
  '/backlog/edit/$gameId/metadata': typeof BacklogEditGameIdMetadataRoute
  '/backlog/edit/$gameId/review': typeof BacklogEditGameIdReviewRoute
  '/backlog/edit/$gameId/': typeof BacklogEditGameIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRouteWithChildren
  '/settings/metadata1': typeof SettingsMetadata1Route
  '/settings/metadata2': typeof SettingsMetadata2Route
  '/settings/metadata3': typeof SettingsMetadata3Route
  '/settings/metadata4': typeof SettingsMetadata4Route
  '/settings/metadata5': typeof SettingsMetadata5Route
  '/settings': typeof SettingsIndexRoute
  '/backlog/edit/$gameId/metadata': typeof BacklogEditGameIdMetadataRoute
  '/backlog/edit/$gameId/review': typeof BacklogEditGameIdReviewRoute
  '/backlog/edit/$gameId': typeof BacklogEditGameIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backlog': typeof BacklogRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/settings/metadata1': typeof SettingsMetadata1Route
  '/settings/metadata2': typeof SettingsMetadata2Route
  '/settings/metadata3': typeof SettingsMetadata3Route
  '/settings/metadata4': typeof SettingsMetadata4Route
  '/settings/metadata5': typeof SettingsMetadata5Route
  '/settings/': typeof SettingsIndexRoute
  '/backlog/edit/$gameId': typeof BacklogEditGameIdRouteWithChildren
  '/backlog/edit/$gameId/metadata': typeof BacklogEditGameIdMetadataRoute
  '/backlog/edit/$gameId/review': typeof BacklogEditGameIdReviewRoute
  '/backlog/edit/$gameId/': typeof BacklogEditGameIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backlog'
    | '/settings'
    | '/settings/metadata1'
    | '/settings/metadata2'
    | '/settings/metadata3'
    | '/settings/metadata4'
    | '/settings/metadata5'
    | '/settings/'
    | '/backlog/edit/$gameId'
    | '/backlog/edit/$gameId/metadata'
    | '/backlog/edit/$gameId/review'
    | '/backlog/edit/$gameId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backlog'
    | '/settings/metadata1'
    | '/settings/metadata2'
    | '/settings/metadata3'
    | '/settings/metadata4'
    | '/settings/metadata5'
    | '/settings'
    | '/backlog/edit/$gameId/metadata'
    | '/backlog/edit/$gameId/review'
    | '/backlog/edit/$gameId'
  id:
    | '__root__'
    | '/'
    | '/backlog'
    | '/settings'
    | '/settings/metadata1'
    | '/settings/metadata2'
    | '/settings/metadata3'
    | '/settings/metadata4'
    | '/settings/metadata5'
    | '/settings/'
    | '/backlog/edit/$gameId'
    | '/backlog/edit/$gameId/metadata'
    | '/backlog/edit/$gameId/review'
    | '/backlog/edit/$gameId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacklogRoute: typeof BacklogRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/metadata5': {
      id: '/settings/metadata5'
      path: '/metadata5'
      fullPath: '/settings/metadata5'
      preLoaderRoute: typeof SettingsMetadata5RouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/metadata4': {
      id: '/settings/metadata4'
      path: '/metadata4'
      fullPath: '/settings/metadata4'
      preLoaderRoute: typeof SettingsMetadata4RouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/metadata3': {
      id: '/settings/metadata3'
      path: '/metadata3'
      fullPath: '/settings/metadata3'
      preLoaderRoute: typeof SettingsMetadata3RouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/metadata2': {
      id: '/settings/metadata2'
      path: '/metadata2'
      fullPath: '/settings/metadata2'
      preLoaderRoute: typeof SettingsMetadata2RouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/metadata1': {
      id: '/settings/metadata1'
      path: '/metadata1'
      fullPath: '/settings/metadata1'
      preLoaderRoute: typeof SettingsMetadata1RouteImport
      parentRoute: typeof SettingsRoute
    }
    '/backlog/edit/$gameId': {
      id: '/backlog/edit/$gameId'
      path: '/edit/$gameId'
      fullPath: '/backlog/edit/$gameId'
      preLoaderRoute: typeof BacklogEditGameIdRouteImport
      parentRoute: typeof BacklogRoute
    }
    '/backlog/edit/$gameId/': {
      id: '/backlog/edit/$gameId/'
      path: '/'
      fullPath: '/backlog/edit/$gameId/'
      preLoaderRoute: typeof BacklogEditGameIdIndexRouteImport
      parentRoute: typeof BacklogEditGameIdRoute
    }
    '/backlog/edit/$gameId/review': {
      id: '/backlog/edit/$gameId/review'
      path: '/review'
      fullPath: '/backlog/edit/$gameId/review'
      preLoaderRoute: typeof BacklogEditGameIdReviewRouteImport
      parentRoute: typeof BacklogEditGameIdRoute
    }
    '/backlog/edit/$gameId/metadata': {
      id: '/backlog/edit/$gameId/metadata'
      path: '/metadata'
      fullPath: '/backlog/edit/$gameId/metadata'
      preLoaderRoute: typeof BacklogEditGameIdMetadataRouteImport
      parentRoute: typeof BacklogEditGameIdRoute
    }
  }
}

interface BacklogEditGameIdRouteChildren {
  BacklogEditGameIdMetadataRoute: typeof BacklogEditGameIdMetadataRoute
  BacklogEditGameIdReviewRoute: typeof BacklogEditGameIdReviewRoute
  BacklogEditGameIdIndexRoute: typeof BacklogEditGameIdIndexRoute
}

const BacklogEditGameIdRouteChildren: BacklogEditGameIdRouteChildren = {
  BacklogEditGameIdMetadataRoute: BacklogEditGameIdMetadataRoute,
  BacklogEditGameIdReviewRoute: BacklogEditGameIdReviewRoute,
  BacklogEditGameIdIndexRoute: BacklogEditGameIdIndexRoute,
}

const BacklogEditGameIdRouteWithChildren =
  BacklogEditGameIdRoute._addFileChildren(BacklogEditGameIdRouteChildren)

interface BacklogRouteChildren {
  BacklogEditGameIdRoute: typeof BacklogEditGameIdRouteWithChildren
}

const BacklogRouteChildren: BacklogRouteChildren = {
  BacklogEditGameIdRoute: BacklogEditGameIdRouteWithChildren,
}

const BacklogRouteWithChildren =
  BacklogRoute._addFileChildren(BacklogRouteChildren)

interface SettingsRouteChildren {
  SettingsMetadata1Route: typeof SettingsMetadata1Route
  SettingsMetadata2Route: typeof SettingsMetadata2Route
  SettingsMetadata3Route: typeof SettingsMetadata3Route
  SettingsMetadata4Route: typeof SettingsMetadata4Route
  SettingsMetadata5Route: typeof SettingsMetadata5Route
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsMetadata1Route: SettingsMetadata1Route,
  SettingsMetadata2Route: SettingsMetadata2Route,
  SettingsMetadata3Route: SettingsMetadata3Route,
  SettingsMetadata4Route: SettingsMetadata4Route,
  SettingsMetadata5Route: SettingsMetadata5Route,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacklogRoute: BacklogRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
